
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafa e Ana
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textlogin = new javax.swing.JTextField();
        senhalogin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Login");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jButton1.setText("Entrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Login:");

        jLabel2.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textlogin)
                                .addComponent(senhalogin, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhalogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        setBounds(50, 50, 352, 366);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
TelaPrincipal.login=0; // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked


//Acesso do Administrador
        if(textlogin.getText().equals("admin") && senhalogin.getText().equals("123")){
             JOptionPane.showMessageDialog(null, "Acesso de Administrador Permitido!");
             textlogin.setText("");
             senhalogin.setText("");
             this.dispose();
             Administrador a = new Administrador();
             TelaPrincipal.escritorio.add(a);
             a.show();
       }else{
          //LOOP para procurar Cadastro
        for(int i=0;i<TelaPrincipal.listUsuarios.size();i++){
            if(textlogin.getText().equals(TelaPrincipal.listUsuarios.get(i).getMatricula())){
                if(senhalogin.getText().equals(TelaPrincipal.listUsuarios.get(i).getSenha())){
                    
                    switch(TelaPrincipal.listUsuarios.get(i).getTipo()){
                    
                        case "Atendente":
                        Atendente a = new Atendente(TelaPrincipal.listUsuarios.get(i).getNome());
                        TelaPrincipal.escritorio.add(a);
                        a.show();break;
                            
                        case "Pizzaiolo":
                        Pizzaiolo p = new Pizzaiolo(TelaPrincipal.listUsuarios.get(i).getNome());
                        TelaPrincipal.escritorio.add(p);
                        p.show();break;
                            
                        case "Entregador":
                        Entregador e = new Entregador(TelaPrincipal.listUsuarios.get(i).getNome());
                        TelaPrincipal.escritorio.add(e);
                        e.show();break;
                    }
                    textlogin.setText("");
                    senhalogin.setText("");
                    this.dispose();
                    
                    
                    return;
                    
            }else{
             JOptionPane.showMessageDialog(null, "Senha Incorreta!");
             return;
                }
                    
            }
                        
        }
       
        if(TelaPrincipal.listUsuarios.size()==0){
    JOptionPane.showMessageDialog(null, "Não Existe Usuarios Cadastrados"); 
          }else{
         JOptionPane.showMessageDialog(null, "Usuario não Existe"); 
                }
        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField senhalogin;
    private javax.swing.JTextField textlogin;
    // End of variables declaration//GEN-END:variables
}
